# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: PyPolo
site_url: https://pypolo.readthedocs.io/
repo_url: https://github.com/Weizhe-Chen/PyPolo
repo_name: GitHub/PyPolo
copyright: Copyright &copy; 2022 - 2023 PyPolo Developers
nav:
  - Home: index.md
  - Installation: installation.md
  - Get Started: get_started.md
  - Framework: framework.md
  - Awesome: awesome.md
  - Contributing: contributing.md
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/social/logo.svg
  favicon: assets/images/social/logo.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - header.autohide
    - navigation.footer
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Weizhe-Chen/PyPolo
  generator: false
